"""empty message

Revision ID: 2075533631cd
Revises: 
Create Date: 2018-07-08 10:16:40.580106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2075533631cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slack_username', sa.String(length=32), nullable=False),
    sa.Column('slack_uid', sa.String(length=32), nullable=False),
    sa.Column('google_token', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('tz', sa.String(length=64), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('team_id', sa.String(length=32), nullable=False),
    sa.Column('token_uri', sa.String(length=128), nullable=True),
    sa.Column('refresh_token', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slack_uid', 'team_id', name='unique_constraint_slack_id_team')
    )
    op.create_index(op.f('ix_Users_email'), 'Users', ['email'], unique=True)
    op.create_index(op.f('ix_Users_first_name'), 'Users', ['first_name'], unique=True)
    op.create_index(op.f('ix_Users_google_token'), 'Users', ['google_token'], unique=True)
    op.create_index(op.f('ix_Users_refresh_token'), 'Users', ['refresh_token'], unique=True)
    op.create_index(op.f('ix_Users_slack_uid'), 'Users', ['slack_uid'], unique=True)
    op.create_index(op.f('ix_Users_team_id'), 'Users', ['team_id'], unique=True)
    op.create_index(op.f('ix_Users_token_uri'), 'Users', ['token_uri'], unique=True)
    op.create_index(op.f('ix_Users_tz'), 'Users', ['tz'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Users_tz'), table_name='Users')
    op.drop_index(op.f('ix_Users_token_uri'), table_name='Users')
    op.drop_index(op.f('ix_Users_team_id'), table_name='Users')
    op.drop_index(op.f('ix_Users_slack_uid'), table_name='Users')
    op.drop_index(op.f('ix_Users_refresh_token'), table_name='Users')
    op.drop_index(op.f('ix_Users_google_token'), table_name='Users')
    op.drop_index(op.f('ix_Users_first_name'), table_name='Users')
    op.drop_index(op.f('ix_Users_email'), table_name='Users')
    op.drop_table('Users')
    # ### end Alembic commands ###
