"""empty message

Revision ID: be7924e987d3
Revises: 
Create Date: 2018-07-11 03:10:44.627588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be7924e987d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slack_username', sa.String(length=32), nullable=False),
    sa.Column('slack_uid', sa.String(length=32), nullable=False),
    sa.Column('google_token', sa.String(length=512), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('tz', sa.String(length=64), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('team_id', sa.String(length=32), nullable=False),
    sa.Column('refresh_token', sa.String(length=128), nullable=True),
    sa.Column('state', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slack_uid', 'team_id', name='unique_constraint_slack_id_team')
    )
    op.create_index(op.f('ix_Users_google_token'), 'Users', ['google_token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Users_google_token'), table_name='Users')
    op.drop_table('Users')
    # ### end Alembic commands ###
