"""empty message

Revision ID: bfdd2aaa1d1b
Revises: 2075533631cd
Create Date: 2018-07-08 10:25:56.926514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfdd2aaa1d1b'
down_revision = '2075533631cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('last_name', sa.String(length=64), nullable=True))
    op.drop_index('ix_Users_email', table_name='Users')
    op.drop_index('ix_Users_first_name', table_name='Users')
    op.drop_index('ix_Users_refresh_token', table_name='Users')
    op.drop_index('ix_Users_slack_uid', table_name='Users')
    op.drop_index('ix_Users_team_id', table_name='Users')
    op.drop_index('ix_Users_tz', table_name='Users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_Users_tz', 'Users', ['tz'], unique=True)
    op.create_index('ix_Users_team_id', 'Users', ['team_id'], unique=True)
    op.create_index('ix_Users_slack_uid', 'Users', ['slack_uid'], unique=True)
    op.create_index('ix_Users_refresh_token', 'Users', ['refresh_token'], unique=True)
    op.create_index('ix_Users_first_name', 'Users', ['first_name'], unique=True)
    op.create_index('ix_Users_email', 'Users', ['email'], unique=True)
    op.drop_column('Users', 'last_name')
    # ### end Alembic commands ###
