"""empty message

Revision ID: eb9f07f0b109
Revises: 
Create Date: 2018-07-05 19:44:06.154859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb9f07f0b109'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slack_username', sa.String(length=32), nullable=False),
    sa.Column('slack_uid', sa.String(length=32), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slack_username', 'slack_uid', name='unique_constraint_slack_id_name')
    )
    op.create_index(op.f('ix_Users_slack_uid'), 'Users', ['slack_uid'], unique=True)
    op.create_index(op.f('ix_Users_slack_username'), 'Users', ['slack_username'], unique=False)
    op.create_index(op.f('ix_Users_token'), 'Users', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Users_token'), table_name='Users')
    op.drop_index(op.f('ix_Users_slack_username'), table_name='Users')
    op.drop_index(op.f('ix_Users_slack_uid'), table_name='Users')
    op.drop_table('Users')
    # ### end Alembic commands ###
